name: Run test suite local

on:
  workflow_dispatch:

jobs:
  run-local-server:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Code
          uses: actions/checkout@v4
  
        - name: Setup python
          uses: actions/setup-python@v4
          with:
            python-version: '3.12'
  
        - name: Install dependencies 
          run: |
            python -m pip install fastapi
            python -m pip install json2html
            python -m pip install requests

        - uses: actions/checkout@v4
        - uses: JarvusInnovations/background-action@v1
        - name: Run local server in bg and testsuite
          run: fastapi dev local_server.py &
          
          wait-on: python testsuite.py local
          
        - name: Archive artifacts
          uses: actions/upload-artifact@v4
          with:
            path: |
              /home/runner/work/codeChallengeCariad/codeChallengeCariad/Artifacts/
              /home/runner/work/codeChallengeCariad/codeChallengeCariad/Reports/
